import TopNav from './TopNav.jsx'
import Footer from './Footer.jsx'
import { Seo } from '../seo.jsx'

const GITHUB_URL = 'https://github.com/RavaniRoshan/niki'

// A real, reproducible run artifact lives in the repo at
// docs/marketing/sample-run/report.md (generated by `niki run` on a small public
// task). It is the "product IS the demo" proof: every claim Niki makes about a
// run is backed by the artifacts it produces.
export default function ProofPage() {
  return (
    <>
      <Seo
        title="Proof · Niki"
        description="Every Niki run leaves a replayable audit trail — report.md, per-agent JSON, and the branch. The product is the demo."
        path="/proof"
      />
      <TopNav />
      <main id="content">
        <section className="section" data-od-id="proof">
          <div className="container" style={{ maxWidth: '72ch' }}>
            <h1 className="heading mb-lg">Proof, not promises</h1>
            <p className="body mb-xl">
              Niki is built so you can verify every claim it makes. A single run leaves behind a
              replayable audit trail — nothing is asserted that the artifacts don&apos;t back.
            </p>

            <h2 className="body-strong mb-lg">What every run produces</h2>
            <ul className="body mb-xl" style={{ lineHeight: 1.9 }}>
              <li><strong>niki/&lt;id&gt; branch</strong> — a real git branch with the diff, never a commit to main.</li>
              <li><strong>report.md</strong> — the human-readable verdict: what each agent decided and why.</li>
              <li><strong>artifacts/*.json</strong> — per-agent decisions (Planner → Coder → Tester → Reviewer), inspectable and reproducible.</li>
              <li><strong>changes.patch</strong> — the exact unified diff.</li>
              <li><strong>test_execution.json</strong> — the real test-suite result, executed inside the sandbox before the branch exists.</li>
              <li><strong>safety_proof</strong> — proof that only the new branch was added; your working tree was untouched.</li>
            </ul>

            <h2 className="body-strong mb-lg">See a real run</h2>
            <p className="body mb-lg">
              A sample run on a small public task is published in the repository:
            </p>
            <p className="body mb-xl">
              <a
                className="btn btn-primary"
                href={`${GITHUB_URL}/blob/master/docs/marketing/sample-run/README.md`}
                target="_blank"
                rel="noopener noreferrer"
              >
                View sample report.md
              </a>
            </p>
            <p className="body mb-xl caption">
              To regenerate it yourself: <code>niki run &quot;Add a GET /health endpoint&quot; --project &lt;your repo&gt;</code> and open <code>.niki/tasks/&lt;id&gt;/report.md</code>.
            </p>

            <h2 className="body-strong mb-lg">Why this matters</h2>
            <p className="body mb-xl">
              Most AI coding tools ask you to trust a diff. Niki gives you the branch, the report,
              and the reasoning behind every agent — review one small, tested, audited change
              instead of a flood of slop.
            </p>
          </div>
        </section>
      </main>
      <Footer />
    </>
  )
}
